package main

import (
	"fmt"
	"os"
	"time"
)

func main() {
	// Create or overwrite a file named "generated.go" in the root project directory
	file, err := os.Create("generated.go")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	// Add a time-based motivational quote dynamically
	hour := time.Now().Hour()
	var quote string
	switch {
	case hour < 12:
		quote = "Good morning, developer! Start your day with clean code!"
	case hour < 18:
		quote = "Keep pushing forward — your code is getting better!"
	default:
		quote = "It’s evening! Great time to refactor and improve your project."
	}

	// Write the generated code into the file
	content := fmt.Sprintf(`// Code generated by scripts/gen.go; DO NOT EDIT.
package main

// GetMotivationalQuote returns a time-based message for the developer
func GetMotivationalQuote() string {
    return "%s"
}
`, quote)

	file.WriteString(content)
}
