package main

import "fmt"

//go:generate stringer -type=Vehicle
type Vehicle int

const (
	Car Vehicle = iota
	Bike
	Truck
	Bus
	Airplane
	Tuktuk
)

func main() {
	vehicles := []Vehicle{Car, Bike, Truck, Bus, Airplane, Tuktuk}

	for _, v := range vehicles {
		// Print the name generated by stringer
		fmt.Println(v)
	}
}
